spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.159.101:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 3333
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.fairing: info
  file: log/blog-pro.log






