spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages

comment.avatar: /images/fairingclub.jpg

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

